### ISSUE TITLE
No metrics have been shown in Grafana

### ISSUE THREAD

**Issue by fghorbel** [Bayer-Group/cf-metrics#12]
Hi, i have followed  literally the documentation, but i cannot see the data from Grafana. 

I got the following outputs from cfmetrics_nozzleprd_1

```
{"timestamp":1504388539.048448563,"process_id":7,"source":"influxdb-firehose-nozzle","log_level":"info","message":"Using the following influx URL http://heka:2010/write?db=cloudfoundry\u0026precision=s","data":null,"file":"/go/src/github.com/MonsantoCo/influxdb-firehose-nozzle/influxdbclient/influxdb_client.go","line":293,"method":"github.com/MonsantoCo/influxdb-firehose-nozzle/influxdbclient.(*Client).seriesURL"}
{"timestamp":1504388539.048573732,"process_id":7,"source":"influxdb-firehose-nozzle","log_level":"info","message":"Posting 652 metrics","data":null,"file":"/go/src/github.com/MonsantoCo/influxdb-firehose-nozzle/influxdbclient/influxdb_client.go","line":262,"method":"github.com/MonsantoCo/influxdb-firehose-nozzle/influxdbclient.(*Client).PostMetrics"
```

Could me tell what is going on please? 

Thank you,
Fadel

**Comment by mjseid** [comment]
Looks like your nozzle is connecting to the firehose correctly, and grabbing metrics.  Its then sending those metrics to Heka, which will process them and depending on the format send them to influxdb.  

You can look in the Heka UI to see if its processing them correctly.  If you go to the http://localhost:4352 and then to the sandboxes tab you should see for your example "influxdb-filter-cf-prd" if everything's working correctly and it will show the data heka is sending to influxdb in influx line format

If that looks good you can run a few influxdb commands to verify the data there is as you'd expect, for example:
```
curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "q=show databases"
curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=cf_prd" --data-urlencode "q=show measurements"
```
If that shows the databases as you'd expect and they are populated with metrics then you just need to tweak something with grafana (maybe a datasource definition)?

Finally I'll point out that if your just starting to look at this project, we are moving towards a new design which uses more recent tooling and is also easier to troubleshoot.  We're still working on a few things, but it's mostly ready to go and so only minor updates before it replaces the main branch.  If you're interested in checking that out, try the "tick" branch of this project and let us know if you have any issues.

**Comment by fghorbel** [comment]
Here what i see from http://localhost:4352-> sandboxes

 recieving-boshhm-filter-np

recieving-boshhm-filter-prd

 recieving-firehose-filter-np

recieving-firehose-filter-prd


and the request 

```
root@sdp-vpc:/mnt/md0/cf-metrics# curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=cf_prd" --data-urlencode "q=show measurements"
{
    "results": [
        {
            "statement_id": 0
        }
    ]
}

```

So, i assume there is something wrong...

Thank you

**Comment by mjseid** [comment]
Ok, if you're seeing those in heka sandbox ( those are the "Deadman" alerts) then heka is filtering out the metrics it's being sent and not forwarding any to influxdb.

I believe you need to update the heka.toml file to match the deployment name of your cloudfoundry/bosh.  By default heka uses the following regex to filter for np (similar examples for bosh or prod settings)
```
Fields[Env] =~ /^cf_.*np.*$/'
```
Which would work if your np cloudfoundry deployment was named "cf_aws_np" or "cf_np".  Can you share what bosh lists as the deployment names for your cf and bosh?

**Comment by fghorbel** [comment]
my  cf deployment name is us-east-1-10.111, i don t have a bosh deployment.

**Comment by mjseid** [comment]
that updated regex looks correct for that deployment name.  

I will say that deployment name seems slightly strange, so just want to make sure we're talking about the same thing.  It's the name that you set inside your cf and digeo ymls ... so if you grep either of those files for _^name:_ is that what it gives you?

For bosh this project gets the deployment name from whatever you set as the prefix for the graphite exporter in the bosh yml:
```
    hm:
      graphite_enabled: true
      graphite:
        port: 2004
        prefix: bosh_aws_np
```

**Comment by mjseid** [comment]
Also you could enable detailed logging for heka by setting this at the bottom of your hekad.toml. It will show how its parsing the metrics as they come in and what its interpreting for the deployment name.

# Log output useful for debugging
[LogOutput]
message_matcher = "Logger == 'bosh-hm-regex' || Logger == 'bosh-alert-decoder' || Logger == 'bosh-consul' || Logger == 'cf-influx-firehose' || Logger == 'HttpListenInput'"
encoder = "RstEncoder"

**Comment by fghorbel** [comment]
Yes, this is the cf deployment name us-east-1-10.11  from ^name in yml files.

Ok, i will try the debugging . thank you

**Comment by fghorbel** [comment]
ok, Thank you, it works now

**Comment by mjseid** [comment]
OK, great that you have it working now.

The 'Application and instance Metrics' dashboard was for pre-diego architecture.  So if you're on diego now, the 'BBS metrics' dashboard is where the equivalent stats for that are.

If you don't setup the bosh metrics, then the affect dashboards  will be the 'VM Level Stats', 'Component Health', and some panels in 'Routing' like CPU % of the routers.

**Comment by fghorbel** [comment]
Hey, 
Maybe i miss something, but i assume, a consul server should run on heka container on port 8500. But i don t see it. however, the consul_event_forwarder bosh setting should forward the Nats messages to this component.

```
 consul_event_forwarder_enabled: true
    consul_event_forwarder:
      host: hostname.of.consul
      events: true
      ttl: 600s
      namespace: ns/
      heartbeats_as_alerts: true

```

**Comment by mjseid** [comment]
You are correct that the event_forwarder is sending nats messages to Heka port 8500.  But instead of running a consul server on the Heka server, Heka is configured to listen on port 8500 as a generic HTTPlisten input.  It then uses some of the other defined filters/parsers to translate the consul formatted http posts into the metrics it saves to influxdb.

**Comment by fghorbel** [comment]
I don t see the port 8500 on heka container. So, how we can reach consul from outside? There is no even a port mapping.

```
        Name                       Command               State                                                           Ports                                                          
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
cfmetrics_grafana_1     /usr/bin/supervisord -c /e ...   Up      0.0.0.0:3000->3000/tcp                                                                                                 
cfmetrics_heka_1        /usr/bin/hekad --config=/e ...   Up      0.0.0.0:2004->2004/tcp, 0.0.0.0:2005->2005/tcp, 0.0.0.0:2010->2010/tcp, 0.0.0.0:4352->4352/tcp, 0.0.0.0:8505->8505/tcp 
cfmetrics_influxdb_1    /run.sh                          Up      0.0.0.0:8083->8083/tcp, 8084/tcp, 0.0.0.0:8086->8086/tcp, 0.0.0.0:8088->8088/tcp                                       
cfmetrics_nozzleprd_1   /usr/bin/supervisord -c /e ...   Up         
```

**Comment by mjseid** [comment]
Looks like the port mapping for heka in your compose.yml got changed to port 8505 instead of 8500.  It should look like this:
```
heka:
  build: ./heka
  ports: 
  - "2004:2004"
  - "2005:2005"
  - "8500:8500"
```

**Comment by fghorbel** [comment]
ok, thanks,

**Comment by fghorbel** [comment]
Hi, 

Could you tell me please, why there is no data in BBS metrics?

Even, when i enable the debugging mode from Heka, i cannot see firehose.bbs.LRPsRunning metric. 

Thank you

**Comment by mjseid** [comment]
Hm, so you get other firehose metrics but not BBS one's?  You are running the diego backend right?

Just to make super sure its not heka filtering those specific bbs metrics out (I don't know how/why it would though) you could look at the firehose from the cli plugin and see if any bbs metrics are coming out of your environment
https://docs.cloudfoundry.org/loggregator/cli-plugin.html

**Comment by fghorbel** [comment]
>so you get other firehose metrics but not BBS one's? 
Yes
>You are running the diego backend right?
Yes

**Comment by XuejiaoZhang** [comment]
@mjseid Hi, as you mentioned in your comment you are moving towards a new design and I couldn't find the `tick` branch, I'm wondering whether the project right now is the one up-to-date.
Another question, what metrics of Application and instances could I expect to get?
Thank you in advance.

**Comment by mjseid** [comment]
Hey, 
   we've updated the master branch with the new code and removed the temporary _tick_ branch.  We made a branch for the old heka code if people still want to use that.

Once things moved to the diego backend, the _Application and Instances_ dashboard was deprecated.  The replacement dashboard for that is the _BBS metrics_ dashboard and the firehose measurements used for that are:
```
firehose.bbs.LRPsDesired
firehose.bbs.LRPsRunning
firehose.bbs.LRPsUnclaimed
firehose.bbs.LRPsMissing
firehose.bbs.CrashedActualLRPs
```

**Comment by ksingh12** [comment]
I am not sure what project we are talking about. I’m probably not the right preson.

Thanks,
Kuldip

**Comment by XuejiaoZhang** [comment]
@mjseid Thank you for your reply.
If I understand correctly, the cf-metrics project is mainly focused on monitoring the health of the components of cf cluster. No detailed metrics of applications such as mem, network traffic, requests count etc. are covered. By the way, do you have any idea how to monitor apps on cloud foundry?

**Comment by mjseid** [comment]
Correct, this project is focused on monitoring the cf cluster itself.  We chose to separate monitoring the platform and the apps themselves, b/c for us the intended audience is different for each.

If you want to use this project to capture those app metrics as well, all you have to do is update the metric types that the firehose nozzle grabs.  Specifically update the following line in the docker-compose.yml from this
```
NOZZLE_EVENT_FILTER=CounterEvent,ValueMetric
``` 
to this  
```
NOZZLE_EVENT_FILTER=CounterEvent,ValueMetric,ContainerMetric,HttpStartStop
```

Or if you're just interested in app metrics, you can use any combination of the nozzle, influx, and grafana to serve up those things [explanation here](https://github.com/MonsantoCo/influxdb-firehose-nozzle).  For apps we also throw in prometheus to get custom metrics using this service discovery mechanism:
https://github.com/MonsantoCo/prom-cf-sd

**Comment by XuejiaoZhang** [comment]
@mjseid Thanks for your answers.

**Comment by mjseid** [comment]
You're welcome.

Since we've strayed a bit from the original intent of this issue, I'm closing this one.  Please open new ones if you have additional questions/issues.  Thanks
